# - name: color_camera
#   type: Ros2ColorCamera
#   frame: ee_camera
#   image_topic: ee_camera_color
#   info_topic: ee_camera_color_info
#   publish_overlay: true

# - name: depth_camera
#   type: Ros2DepthCamera
#   frame: ee_camera
#   image_topic: ee_camera_depth
#   info_topic: ee_camera_depth_info
#   scale: 1.0

- name: color_3rd
  type: Ros2ColorCamera
  frame: 3rd_person
  image_topic: color_3rd
  info_topic: color_3rd_info
  publish_overlay: true

- name: depth_3rd
  type: Ros2DepthCamera
  frame: 3rd_person
  image_topic: depth_3rd
  info_topic: depth_3rd_info
  scale: 1.0
